import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const translations = {
    en: {
      // Common
      home: 'Home',
      products: 'Products',
      dietPlans: 'Diet Plans',
      calculator: 'Calculator',
      profile: 'Profile',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      // Auth Pages
      signInToAccount: 'Sign in to your account',
      createAccount: 'Create your account',
      or: 'Or',
      createNewAccount: 'create a new account',
      signInExisting: 'sign in to your existing account',
      emailAddress: 'Email address',
      email: 'Email',
      password: 'Password',
      fullName: 'Full Name',
      phone: 'Phone',
      address: 'Address',
      confirmPassword: 'Confirm Password',
      enterFullName: 'Enter your full name',
      enterEmail: 'Enter your email',
      enterPhone: 'Enter your phone number',
      enterAddress: 'Enter your address',
      enterPassword: 'Enter your password',
      confirmYourPassword: 'Confirm your password',
      signingIn: 'Signing in...',
      signIn: 'Sign in',
      creatingAccount: 'Creating account...',
      createAccountButton: 'Create account',
      passwordsDoNotMatch: 'Passwords do not match',
      passwordMinLength: 'Password must be at least 6 characters',
      // Amma's Kitchen
      ammasKitchen: "Amma's Kitchen",
      buildYourPlate: 'Build Your Plate',
      // Daily Tips
      dailyTip: 'Daily Tip',
      oneChange: 'One Change Today',
      // Meal Logging
      logMeal: 'Log Meal',
      takePhoto: 'Take Photo',
      // Plates
      generatePlate: 'Generate Plate',
      busyLifeHack: 'Busy Life Hack',
      // Sri Lankan Plates Page
      healthGoal: 'Health Goal',
      targetCalories: 'Target Calories',
      generateNewPlate: 'Generate New Plate',
      generating: 'Generating...',
      plateContents: 'Plate Contents',
      nutritionSummary: 'Nutrition Summary',
      totalCalories: 'Total Calories',
      protein: 'Protein',
      carbs: 'Carbs',
      fat: 'Fat',
      fiber: 'Fiber',
      suggestedSubstitutions: 'Suggested Substitutions',
      prepTime: 'Prep Time',
      minutes: 'minutes',
      // Calculator Page
      nutritionCalculator: 'Nutrition Calculator',
      addTraditionalFoods: 'Add Traditional Foods',
      searchFoods: 'Search foods...',
      loadingFoods: 'Loading foods...',
      selectedFoods: 'Selected Foods',
      noFoodsSelected: 'No foods selected',
      quantity: 'Quantity',
      remove: 'Remove',
      add: 'Add',
      added: 'Added',
      calories: 'Calories',
      carbohydrates: 'Carbohydrates',
      // Common Actions
      tools: 'Tools',
      welcome: 'Welcome to Smart Diet SL',
      trustedAdvisor: 'Your trusted nutrition advisor for healthy Sri Lankan diets',
      calculateNutrition: 'Calculate Nutrition',
      getPersonalizedPlates: 'Get personalized Sri Lankan meal plates based on your health goals',
      // Goal Types
      weightLoss: 'Weight Loss',
      diabetesManagement: 'Diabetes Management',
      weightGain: 'Weight Gain',
      generalHealth: 'General Health',
      // Home Page
      whyChooseUs: 'Why Choose Us?',
      calculateNutritionIntake: 'Calculate your daily nutrition intake with our easy-to-use calculator',
      followPersonalizedPlans: 'Follow personalized diet plans designed for Sri Lankan cuisine',
      browseProducts: 'Browse our wide selection of healthy products and ingredients',
      traditionalFoods: 'Traditional Foods',
      // Diet Plans Page
      recommendedDietPlans: 'Recommended Diet Plans',
      loadingDietPlans: 'Loading diet plans...',
      noDietPlansAvailable: 'No diet plans available',
      duration: 'Duration',
      days: 'days',
      meals: 'Meals',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
      all: 'All',
      weightLossCategory: 'Weight Loss',
      weightGainCategory: 'Weight Gain',
      diabetic: 'Diabetic',
      vegetarian: 'Vegetarian',
      general: 'General',
      athletic: 'Athletic',
      failedToFetchDietPlans: 'Failed to fetch diet plans',
      // Profile Page
      myProfile: 'My Profile',
      profilePicture: 'Profile Picture',
      updateProfile: 'Update Profile',
      updating: 'Updating...',
      profileUpdatedSuccess: 'Profile updated successfully',
      failedToUpdateProfile: 'Failed to update profile',
      // Meal Logging Page
      mealType: 'Meal Type',
      snack: 'Snack',
      recognizedItems: 'Recognized Items',
      pleaseVerify: 'Please verify and add any missing items below',
      addItemsManually: 'Add Items Manually',
      addItem: '+ Add Item',
      foodName: 'Food name',
      portion: 'Portion',
      notesOptional: 'Notes (optional)',
      additionalNotes: 'Any additional notes about your meal...',
      logging: 'Logging...',
      mealRecognized: 'Meal recognized! Please verify and add any missing items.',
      pleaseAddImageOrItems: 'Please add an image or manual items',
      mealLoggedSuccess: 'Meal logged successfully!',
      failedToLogMeal: 'Failed to log meal',
      remove: 'Remove',
      confidence: 'confidence',
      // Diet Planner Page
      aiDietPlanner: 'AI Diet Planner',
      getPersonalizedPlan: 'Get a personalized 7-day diet plan based on your health profile',
      yourHealthInformation: 'Your Health Information',
      weight: 'Weight (kg)',
      height: 'Height (cm)',
      age: 'Age',
      yourBMI: 'Your BMI',
      category: 'Category',
      medicalInformation: 'Medical Information',
      bloodPressure: 'Blood Pressure (mmHg)',
      bloodSugarLevel: 'Blood Sugar Level / Diabetes',
      bodyType: 'Body Type',
      selectBodyType: 'Select body type',
      ectomorph: 'Ectomorph (Naturally thin, fast metabolism)',
      mesomorph: 'Mesomorph (Naturally athletic, balanced)',
      endomorph: 'Endomorph (Naturally stocky, slower metabolism)',
      activityLevel: 'Activity Level',
      low: 'Low (Little or no exercise)',
      moderate: 'Moderate (Exercise 3-5 days/week)',
      high: 'High (Exercise 6-7 days/week)',
      generatingPlan: 'Generating Plan...',
      generateMyDietPlan: 'Generate My Diet Plan',
      clearPlan: 'Clear Plan',
      fillFormToGenerate: 'Fill out the form to generate your personalized diet plan.',
      generatingPersonalizedPlan: 'Generating your personalized diet plan...',
      dietPlanReady: 'Your diet plan is ready!',
      failedToGeneratePlan: 'Failed to generate diet plan',
      pleaseFillRequired: 'Please fill in Weight, Height, and Age (required fields)',
      yourPersonalizedPlan: 'Your Personalized 7-Day Diet Plan',
      planId: 'Plan ID',
      previousPlans: 'Previous Plans',
      created: 'Created',
      viewFullPlan: 'View Full Plan',
      normal: 'Normal',
      underweight: 'Underweight',
      overweight: 'Overweight',
      obese: 'Obese',
      // Products Page
      ourProducts: 'Our Products',
      searchProducts: 'Search products...',
      loadingProducts: 'Loading products...',
      noProductsFound: 'No products found',
      addToCart: 'Add to Cart',
      productAddedToCart: 'Product added to cart',
      back: '← Back',
      backToProducts: 'Back to Products',
      productNotFound: 'Product not found',
      nutritionInformation: 'Nutrition Information (per 100g)',
      per100g: 'per 100g',
      // Product Categories
      vegetables: 'Vegetables',
      fruits: 'Fruits',
      grains: 'Grains',
      proteins: 'Proteins',
      dairy: 'Dairy',
      spices: 'Spices',
      other: 'Other',
    },
    si: {
      // Common
      home: 'මුල් පිටුව',
      products: 'නිෂ්පාදන',
      dietPlans: 'ආහාර සැලසුම්',
      calculator: 'පෝෂණ ගණකය',
      profile: 'පැතිකඩ',
      login: 'පිවිසීම',
      register: 'ලියාපදිංචි වන්න',
      logout: 'පිටවීම',
      // Auth Pages
      signInToAccount: 'ඔබේ ගිණුමට පිවිසීම',
      createAccount: 'ඔබේ ගිණුම සාදන්න',
      or: 'හෝ',
      createNewAccount: 'නව ගිණුමක් සාදන්න',
      signInExisting: 'ඔබේ පවතින ගිණුමට පිවිසීම',
      emailAddress: 'විද්‍යුත් තැපැල් ලිපිනය',
      email: 'විද්‍යුත් තැපැල්',
      password: 'මුරපදය',
      fullName: 'සම්පූර්ණ නම',
      phone: 'දුරකථන',
      address: 'ලිපිනය',
      confirmPassword: 'මුරපදය තහවුරු කරන්න',
      enterFullName: 'ඔබේ සම්පූර්ණ නම ඇතුළත් කරන්න',
      enterEmail: 'ඔබේ විද්‍යුත් තැපැල් ලිපිනය ඇතුළත් කරන්න',
      enterPhone: 'ඔබේ දුරකථන අංකය ඇතුළත් කරන්න',
      enterAddress: 'ඔබේ ලිපිනය ඇතුළත් කරන්න',
      enterPassword: 'ඔබේ මුරපදය ඇතුළත් කරන්න',
      confirmYourPassword: 'ඔබේ මුරපදය තහවුරු කරන්න',
      signingIn: 'පිවිසෙමින්...',
      signIn: 'පිවිසීම',
      creatingAccount: 'ගිණුම සාදමින්...',
      createAccountButton: 'ගිණුම සාදන්න',
      passwordsDoNotMatch: 'මුරපද නොගැලපේ',
      passwordMinLength: 'මුරපදය අවම වශයෙන් අක්ෂර 6 ක් විය යුතුය',
      // Amma's Kitchen
      ammasKitchen: 'අම්මාගේ අවන්',
      buildYourPlate: 'ඔබේ ආහාර වේල් සාදන්න',
      // Daily Tips
      dailyTip: 'දිනපතා ඉඟිය',
      oneChange: 'අද එක වෙනසක්',
      // Meal Logging
      logMeal: 'ආහාර සටහන් කරන්න',
      takePhoto: 'ඡායාරූපයක් ගන්න',
      // Plates
      generatePlate: 'ආහාර වේල සකසන්න',
      busyLifeHack: 'කාර්යබහුල ජීවිතයේ උපක්‍රමය',
      // Sri Lankan Plates Page
      healthGoal: 'සෞඛ්‍ය අරමුණ',
      targetCalories: 'ඉලක්ක කැලරි',
      generateNewPlate: 'නව ආහාර වේල සකසන්න',
      generating: 'සාදමින්...',
      plateContents: 'ආහාර වේලේ අන්තර්ගතය',
      nutritionSummary: 'පෝෂණ සාරාංශය',
      totalCalories: 'සම්පූර්ණ කැලරි',
      protein: 'ප්‍රෝටීන්',
      carbs: 'කාබෝහයිඩ්‍රේට්',
      fat: 'මේදය',
      fiber: 'තන්තු',
      suggestedSubstitutions: 'යෝජිත ආදේශන',
      prepTime: 'සූදානම් කිරීමේ කාලය',
      minutes: 'විනාඩි',
      // Calculator Page
      nutritionCalculator: 'පෝෂණ ගණකය',
      addTraditionalFoods: 'සාම්ප්‍රදායික ආහාර එකතු කරන්න',
      searchFoods: 'ආහාර සොයන්න...',
      loadingFoods: 'ආහාර පූරණය වෙමින්...',
      selectedFoods: 'තෝරාගත් ආහාර',
      noFoodsSelected: 'ආහාර තෝරාගෙන නැත',
      quantity: 'ප්‍රමාණය',
      remove: 'ඉවත් කරන්න',
      add: 'එකතු කරන්න',
      added: 'එකතු කරන ලදී',
      calories: 'කැලරි',
      carbohydrates: 'කාබෝහයිඩ්‍රේට්',
      // Common Actions
      tools: 'උපකරණ',
      welcome: 'Smart Diet SL වෙත සාදරයෙන් පිළිගනිමු',
      trustedAdvisor: 'ශ්‍රී ලංකා ආහාර සඳහා ඔබේ විශ්වාසදායක පෝෂණ උපදේශක',
      calculateNutrition: 'පෝෂණ ගණනය කරන්න',
      getPersonalizedPlates: 'ඔබේ සෞඛ්‍ය අරමුණු මත පදනම්ව පුද්ගලීකරණය කළ ශ්‍රී ලංකා ආහාර වේල් ලබා ගන්න',
      // Goal Types
      weightLoss: 'බර අඩු කිරීම',
      diabetesManagement: 'මීටැඹියාව කළමනාකරණය',
      weightGain: 'බර වැඩි කිරීම',
      generalHealth: 'සාමාන්‍ය සෞඛ්‍යය',
      // Home Page
      whyChooseUs: 'අපව තෝරාගන්නේ ඇයි?',
      calculateNutritionIntake: 'අපගේ පහසු ගණකය සමඟ ඔබේ දිනපතා පෝෂණ ප්‍රමාණය ගණනය කරන්න',
      followPersonalizedPlans: 'ශ්‍රී ලංකා ආහාර සඳහා නිර්මාණය කරන ලද පුද්ගලීකරණය කළ ආහාර සැලසුම් අනුගමනය කරන්න',
      browseProducts: 'අපගේ පුළුල් සෞඛ්‍ය සම්පන්න නිෂ්පාදන සහ අමුද්‍රව්‍ය තෝරාගන්න',
      traditionalFoods: 'සාම්ප්‍රදායික ආහාර',
      // Diet Plans Page
      recommendedDietPlans: 'නිර්දේශිත ආහාර සැලසුම්',
      loadingDietPlans: 'ආහාර සැලසුම් පූරණය වෙමින්...',
      noDietPlansAvailable: 'ආහාර සැලසුම් නොමැත',
      duration: 'කාලසීමාව',
      days: 'දින',
      meals: 'ආහාර',
      breakfast: 'උදේ ආහාර',
      lunch: 'දවල් ආහාර',
      dinner: 'රාත්‍රී ආහාර',
      all: 'සියල්ල',
      weightLossCategory: 'බර අඩු කිරීම',
      weightGainCategory: 'බර වැඩි කිරීම',
      diabetic: 'මීටැඹියාව',
      vegetarian: 'ශාකාහාරී',
      general: 'සාමාන්‍ය',
      athletic: 'ක්‍රීඩා',
      failedToFetchDietPlans: 'ආහාර සැලසුම් ලබා ගැනීමට අසමත් විය',
      // Profile Page
      myProfile: 'මගේ පැතිකඩ',
      profilePicture: 'පැතිකඩ පින්තූරය',
      updateProfile: 'පැතිකඩ යාවත්කාලීන කරන්න',
      updating: 'යාවත්කාලීන කරමින්...',
      profileUpdatedSuccess: 'පැතිකඩ සාර්ථකව යාවත්කාලීන කරන ලදී',
      failedToUpdateProfile: 'පැතිකඩ යාවත්කාලීන කිරීමට අසමත් විය',
      // Meal Logging Page
      mealType: 'ආහාර වර්ගය',
      snack: 'ප්‍රලාප',
      recognizedItems: 'හඳුනාගත් අයිතම',
      pleaseVerify: 'කරුණාකර සත්‍යාපනය කර අතුරුදහන් වූ අයිතම එකතු කරන්න',
      addItemsManually: 'අයිතම අතින් එකතු කරන්න',
      addItem: '+ අයිතමයක් එකතු කරන්න',
      foodName: 'ආහාර නම',
      portion: 'ප්‍රමාණය',
      notesOptional: 'සටහන් (විකල්ප)',
      additionalNotes: 'ඔබේ ආහාරය පිළිබඳ අමතර සටහන්...',
      logging: 'සටහන් කරමින්...',
      mealRecognized: 'ආහාරය හඳුනාගන්නා ලදී! කරුණාකර සත්‍යාපනය කර අතුරුදහන් වූ අයිතම එකතු කරන්න.',
      pleaseAddImageOrItems: 'කරුණාකර රූපයක් හෝ අතින් අයිතම එකතු කරන්න',
      mealLoggedSuccess: 'ආහාරය සාර්ථකව සටහන් කරන ලදී!',
      failedToLogMeal: 'ආහාරය සටහන් කිරීමට අසමත් විය',
      remove: 'ඉවත් කරන්න',
      confidence: 'විශ්වාසය',
      // Diet Planner Page
      aiDietPlanner: 'AI ආහාර සැලසුම්කරු',
      getPersonalizedPlan: 'ඔබේ සෞඛ්‍ය පැතිකඩ මත පදනම්ව පුද්ගලීකරණය කළ දින 7 ක ආහාර සැලසුමක් ලබා ගන්න',
      yourHealthInformation: 'ඔබේ සෞඛ්‍ය තොරතුරු',
      weight: 'බර (කිලෝග්‍රෑම්)',
      height: 'උස (සෙන්ටිමීටර)',
      age: 'වයස',
      yourBMI: 'ඔබේ BMI',
      category: 'වර්ගය',
      medicalInformation: 'වෛද්‍ය තොරතුරු',
      bloodPressure: 'රුධිර පීඩනය (mmHg)',
      bloodSugarLevel: 'රුධිර සීනි මට්ටම / මීටැඹියාව',
      bodyType: 'ශරීර වර්ගය',
      selectBodyType: 'ශරීර වර්ගය තෝරන්න',
      ectomorph: 'එක්ටොමෝර්ෆ් (ස්වභාවිකව සිහින්, වේගවත් චයනය)',
      mesomorph: 'මෙසොමෝර්ෆ් (ස්වභාවිකව ක්‍රීඩාකාරී, සමතුලිත)',
      endomorph: 'එන්ඩොමෝර්ෆ් (ස්වභාවිකව ඝන, මන්දගාමී චයනය)',
      activityLevel: 'ක්‍රියාකාරකම් මට්ටම',
      low: 'අඩු (සුළු හෝ ක්‍රියාකාරකම් නැත)',
      moderate: 'මධ්‍යස්ථ (සතියකට දින 3-5 ක් ව්‍යායාම)',
      high: 'ඉහළ (සතියකට දින 6-7 ක් ව්‍යායාම)',
      generatingPlan: 'සැලසුම සාදමින්...',
      generateMyDietPlan: 'මගේ ආහාර සැලසුම සාදන්න',
      clearPlan: 'සැලසුම මකන්න',
      fillFormToGenerate: 'ඔබේ පුද්ගලීකරණය කළ ආහාර සැලසුම සාදා ගැනීමට පෝරමය පුරවන්න.',
      generatingPersonalizedPlan: 'ඔබේ පුද්ගලීකරණය කළ ආහාර සැලසුම සාදමින්...',
      dietPlanReady: 'ඔබේ ආහාර සැලසුම සූදානම්!',
      failedToGeneratePlan: 'ආහාර සැලසුම සාදා ගැනීමට අසමත් විය',
      pleaseFillRequired: 'කරුණාකර බර, උස සහ වයස පුරවන්න (අවශ්‍ය ක්ෂේත්‍ර)',
      yourPersonalizedPlan: 'ඔබේ පුද්ගලීකරණය කළ දින 7 ක ආහාර සැලසුම',
      planId: 'සැලසුම් ID',
      previousPlans: 'පෙර සැලසුම්',
      created: 'සාදන ලදී',
      viewFullPlan: 'සම්පූර්ණ සැලසුම බලන්න',
      normal: 'සාමාන්‍ය',
      underweight: 'අඩු බර',
      overweight: 'අධික බර',
      obese: 'මේදවතාවය',
      // Products Page
      ourProducts: 'අපගේ නිෂ්පාදන',
      searchProducts: 'නිෂ්පාදන සොයන්න...',
      loadingProducts: 'නිෂ්පාදන පූරණය වෙමින්...',
      noProductsFound: 'නිෂ්පාදන හමු නොවීය',
      addToCart: 'කරත්තයට එකතු කරන්න',
      productAddedToCart: 'නිෂ්පාදනය කරත්තයට එකතු කරන ලදී',
      back: '← ආපසු',
      backToProducts: 'නිෂ්පාදන වෙත ආපසු',
      productNotFound: 'නිෂ්පාදනය හමු නොවීය',
      nutritionInformation: 'පෝෂණ තොරතුරු (100g කට)',
      per100g: '100g කට',
      // Product Categories
      vegetables: 'එළවළු',
      fruits: 'පළතුරු',
      grains: 'ධාන්‍ය',
      proteins: 'ප්‍රෝටීන්',
      dairy: 'කිරි නිෂ්පාදන',
      spices: 'කුළුබඩු',
      other: 'වෙනත්',
    },
    ta: {
      // Common
      home: 'வீடு',
      products: 'தயாரிப்புகள்',
      dietPlans: 'உணவு திட்டங்கள்',
      calculator: 'ஊட்டச்சத்து கணிப்பான்',
      profile: 'சுயவிவரம்',
      login: 'உள்நுழைய',
      register: 'பதிவு செய்',
      logout: 'வெளியேறு',
      // Auth Pages
      signInToAccount: 'உங்கள் கணக்கில் உள்நுழைய',
      createAccount: 'உங்கள் கணக்கை உருவாக்கவும்',
      or: 'அல்லது',
      createNewAccount: 'புதிய கணக்கை உருவாக்கவும்',
      signInExisting: 'உங்கள் இருக்கும் கணக்கில் உள்நுழைய',
      emailAddress: 'மின்னஞ்சல் முகவரி',
      email: 'மின்னஞ்சல்',
      password: 'கடவுச்சொல்',
      fullName: 'முழு பெயர்',
      phone: 'தொலைபேசி',
      address: 'முகவரி',
      confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      enterFullName: 'உங்கள் முழு பெயரை உள்ளிடவும்',
      enterEmail: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      enterPhone: 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      enterAddress: 'உங்கள் முகவரியை உள்ளிடவும்',
      enterPassword: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      confirmYourPassword: 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      signingIn: 'உள்நுழைகிறது...',
      signIn: 'உள்நுழைய',
      creatingAccount: 'கணக்கு உருவாக்கப்படுகிறது...',
      createAccountButton: 'கணக்கை உருவாக்கவும்',
      passwordsDoNotMatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
      passwordMinLength: 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்',
      // Amma's Kitchen
      ammasKitchen: 'அம்மாவின் சமையலறை',
      buildYourPlate: 'உங்கள் தட்டை உருவாக்கவும்',
      // Daily Tips
      dailyTip: 'தினசரி உதவிக்குறிப்பு',
      oneChange: 'இன்று ஒரு மாற்றம்',
      // Meal Logging
      logMeal: 'உணவை பதிவு செய்',
      takePhoto: 'படம் எடு',
      // Plates
      generatePlate: 'தட்டை உருவாக்கவும்',
      busyLifeHack: 'பிஸிய வாழ்க்கை தந்திரம்',
      // Sri Lankan Plates Page
      healthGoal: 'சுகாதார இலக்கு',
      targetCalories: 'இலக்கு கலோரிகள்',
      generateNewPlate: 'புதிய தட்டை உருவாக்கவும்',
      generating: 'உருவாக்குகிறது...',
      plateContents: 'தட்டின் உள்ளடக்கம்',
      nutritionSummary: 'ஊட்டச்சத்து சுருக்கம்',
      totalCalories: 'மொத்த கலோரிகள்',
      protein: 'புரதம்',
      carbs: 'கார்போஹைட்ரேட்டுகள்',
      fat: 'கொழுப்பு',
      fiber: 'நார்ச்சத்து',
      suggestedSubstitutions: 'பரிந்துரைக்கப்பட்ட மாற்றீடுகள்',
      prepTime: 'தயாரிப்பு நேரம்',
      minutes: 'நிமிடங்கள்',
      // Calculator Page
      nutritionCalculator: 'ஊட்டச்சத்து கணிப்பான்',
      addTraditionalFoods: 'பாரம்பரிய உணவுகளைச் சேர்க்கவும்',
      searchFoods: 'உணவுகளைத் தேடு...',
      loadingFoods: 'உணவுகள் ஏற்றப்படுகின்றன...',
      selectedFoods: 'தேர்ந்தெடுக்கப்பட்ட உணவுகள்',
      noFoodsSelected: 'உணவுகள் தேர்ந்தெடுக்கப்படவில்லை',
      quantity: 'அளவு',
      remove: 'அகற்று',
      add: 'சேர்',
      added: 'சேர்க்கப்பட்டது',
      calories: 'கலோரிகள்',
      carbohydrates: 'கார்போஹைட்ரேட்டுகள்',
      // Common Actions
      tools: 'கருவிகள்',
      welcome: 'Smart Diet SL க்கு வரவேற்கிறோம்',
      trustedAdvisor: 'ஆரோக்கியமான இலங்கை உணவுகளுக்கான உங்கள் நம்பகமான ஊட்டச்சத்து ஆலோசகர்',
      calculateNutrition: 'ஊட்டச்சத்தைக் கணக்கிடுங்கள்',
      getPersonalizedPlates: 'உங்கள் சுகாதார இலக்குகளின் அடிப்படையில் தனிப்பயனாக்கப்பட்ட இலங்கை உணவு தட்டுகளைப் பெறுங்கள்',
      // Goal Types
      weightLoss: 'எடை குறைத்தல்',
      diabetesManagement: 'நீரிழிவு நோய் மேலாண்மை',
      weightGain: 'எடை அதிகரித்தல்',
      generalHealth: 'பொது சுகாதாரம்',
      // Home Page
      whyChooseUs: 'ஏன் நம்மை தேர்வு செய்ய வேண்டும்?',
      calculateNutritionIntake: 'எங்கள் எளிதான கணிப்பானைப் பயன்படுத்தி உங்கள் தினசரி ஊட்டச்சத்து உட்கொள்ளலைக் கணக்கிடுங்கள்',
      followPersonalizedPlans: 'இலங்கை உணவுக்காக வடிவமைக்கப்பட்ட தனிப்பயனாக்கப்பட்ட உணவு திட்டங்களைப் பின்பற்றுங்கள்',
      browseProducts: 'எங்கள் பரந்த ஆரோக்கியமான தயாரிப்புகள் மற்றும் பொருட்களின் தேர்வை உலாவுங்கள்',
      traditionalFoods: 'பாரம்பரிய உணவுகள்',
      // Diet Plans Page
      recommendedDietPlans: 'பரிந்துரைக்கப்பட்ட உணவு திட்டங்கள்',
      loadingDietPlans: 'உணவு திட்டங்கள் ஏற்றப்படுகின்றன...',
      noDietPlansAvailable: 'உணவு திட்டங்கள் இல்லை',
      duration: 'கால அளவு',
      days: 'நாட்கள்',
      meals: 'உணவுகள்',
      breakfast: 'காலை உணவு',
      lunch: 'மதிய உணவு',
      dinner: 'இரவு உணவு',
      all: 'அனைத்தும்',
      weightLossCategory: 'எடை குறைத்தல்',
      weightGainCategory: 'எடை அதிகரித்தல்',
      diabetic: 'நீரிழிவு',
      vegetarian: 'சைவ',
      general: 'பொது',
      athletic: 'விளையாட்டு',
      failedToFetchDietPlans: 'உணவு திட்டங்களைப் பெற முடியவில்லை',
      // Profile Page
      myProfile: 'எனது சுயவிவரம்',
      profilePicture: 'சுயவிவர படம்',
      updateProfile: 'சுயவிவரத்தை புதுப்பிக்கவும்',
      updating: 'புதுப்பிக்கிறது...',
      profileUpdatedSuccess: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      failedToUpdateProfile: 'சுயவிவரத்தை புதுப்பிக்க முடியவில்லை',
      // Meal Logging Page
      mealType: 'உணவு வகை',
      snack: 'சிற்றுண்டி',
      recognizedItems: 'அங்கீகரிக்கப்பட்ட பொருட்கள்',
      pleaseVerify: 'தயவுசெய்து சரிபார்த்து விடுபட்ட பொருட்களைச் சேர்க்கவும்',
      addItemsManually: 'பொருட்களை கைமுறையாக சேர்க்கவும்',
      addItem: '+ பொருளை சேர்',
      foodName: 'உணவு பெயர்',
      portion: 'பகுதி',
      notesOptional: 'குறிப்புகள் (விருப்பமானது)',
      additionalNotes: 'உங்கள் உணவு பற்றிய கூடுதல் குறிப்புகள்...',
      logging: 'பதிவு செய்கிறது...',
      mealRecognized: 'உணவு அங்கீகரிக்கப்பட்டது! தயவுசெய்து சரிபார்த்து விடுபட்ட பொருட்களைச் சேர்க்கவும்.',
      pleaseAddImageOrItems: 'தயவுசெய்து படம் அல்லது கைமுறை பொருட்களைச் சேர்க்கவும்',
      mealLoggedSuccess: 'உணவு வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
      failedToLogMeal: 'உணவை பதிவு செய்ய முடியவில்லை',
      remove: 'அகற்று',
      confidence: 'நம்பிக்கை',
      // Diet Planner Page
      aiDietPlanner: 'AI உணவு திட்டமிடுபவர்',
      getPersonalizedPlan: 'உங்கள் சுகாதார சுயவிவரத்தின் அடிப்படையில் தனிப்பயனாக்கப்பட்ட 7 நாள் உணவு திட்டத்தைப் பெறுங்கள்',
      yourHealthInformation: 'உங்கள் சுகாதார தகவல்',
      weight: 'எடை (கிலோ)',
      height: 'உயரம் (செ.மீ)',
      age: 'வயது',
      yourBMI: 'உங்கள் BMI',
      category: 'வகை',
      medicalInformation: 'மருத்துவ தகவல்',
      bloodPressure: 'இரத்த அழுத்தம் (mmHg)',
      bloodSugarLevel: 'இரத்த சர்க்கரை அளவு / நீரிழிவு',
      bodyType: 'உடல் வகை',
      selectBodyType: 'உடல் வகையைத் தேர்ந்தெடுக்கவும்',
      ectomorph: 'எக்டோமார்ஃப் (இயற்கையாக மெல்லிய, வேகமான வளர்சிதைமாற்றம்)',
      mesomorph: 'மெசோமார்ஃப் (இயற்கையாக விளையாட்டு, சமநிலை)',
      endomorph: 'எண்டோமார்ஃப் (இயற்கையாக கனமான, மெதுவான வளர்சிதைமாற்றம்)',
      activityLevel: 'செயல்பாட்டு நிலை',
      low: 'குறைந்த (குறைந்த அல்லது எந்த உடற்பயிற்சியும் இல்லை)',
      moderate: 'மிதமான (வாரத்திற்கு 3-5 நாட்கள் உடற்பயிற்சி)',
      high: 'உயர் (வாரத்திற்கு 6-7 நாட்கள் உடற்பயிற்சி)',
      generatingPlan: 'திட்டம் உருவாக்குகிறது...',
      generateMyDietPlan: 'எனது உணவு திட்டத்தை உருவாக்கவும்',
      clearPlan: 'திட்டத்தை அழிக்கவும்',
      fillFormToGenerate: 'உங்கள் தனிப்பயனாக்கப்பட்ட உணவு திட்டத்தை உருவாக்க படிவத்தை நிரப்பவும்.',
      generatingPersonalizedPlan: 'உங்கள் தனிப்பயனாக்கப்பட்ட உணவு திட்டத்தை உருவாக்குகிறது...',
      dietPlanReady: 'உங்கள் உணவு திட்டம் தயாராக உள்ளது!',
      failedToGeneratePlan: 'உணவு திட்டத்தை உருவாக்க முடியவில்லை',
      pleaseFillRequired: 'தயவுசெய்து எடை, உயரம் மற்றும் வயதை நிரப்பவும் (தேவையான புலங்கள்)',
      yourPersonalizedPlan: 'உங்கள் தனிப்பயனாக்கப்பட்ட 7 நாள் உணவு திட்டம்',
      planId: 'திட்ட ID',
      previousPlans: 'முந்தைய திட்டங்கள்',
      created: 'உருவாக்கப்பட்டது',
      viewFullPlan: 'முழு திட்டத்தைக் காண்க',
      normal: 'இயல்பான',
      underweight: 'குறைந்த எடை',
      overweight: 'அதிக எடை',
      obese: 'உடல்பருமன்',
      // Products Page
      ourProducts: 'எங்கள் தயாரிப்புகள்',
      searchProducts: 'தயாரிப்புகளைத் தேடு...',
      loadingProducts: 'தயாரிப்புகள் ஏற்றப்படுகின்றன...',
      noProductsFound: 'தயாரிப்புகள் கிடைக்கவில்லை',
      addToCart: 'கார்ட்டில் சேர்',
      productAddedToCart: 'தயாரிப்பு கார்ட்டில் சேர்க்கப்பட்டது',
      back: '← பின்',
      backToProducts: 'தயாரிப்புகளுக்குத் திரும்பு',
      productNotFound: 'தயாரிப்பு கிடைக்கவில்லை',
      nutritionInformation: 'ஊட்டச்சத்து தகவல் (100g க்கு)',
      per100g: '100g க்கு',
      // Product Categories
      vegetables: 'காய்கறிகள்',
      fruits: 'பழங்கள்',
      grains: 'தானியங்கள்',
      proteins: 'புரதங்கள்',
      dairy: 'பால் பொருட்கள்',
      spices: 'மசாலாப் பொருட்கள்',
      other: 'மற்றவை',
    },
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};


